defaults:
  - sampler: uncond
  - reward: none
  - _self_

model_path: model_v2.ckpt
output_dir: outputs
num_samples: 100
softmax_temp: 1.0
randomness: 0.3
min_add_len: 60
seed: 0

hydra:
  run:
    dir: .
  output_subdir: null
